"""empty message

Revision ID: b763fdfe7c63
Revises:
Create Date: 2020-10-19 20:07:04.120668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b763fdfe7c63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('paragraph', sa.Text(), nullable=False),
                    sa.Column('intent', sa.String(length=25), nullable=False),
                    sa.Column('context', sa.String(length=25), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('response',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('response', sa.Text(), nullable=False),
                    sa.Column('intent', sa.String(length=25), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('user',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('username', sa.String(
                        length=20), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('password', sa.String(
                        length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user',
                    ['username'], unique=True)
    op.create_table('apikey',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('key', sa.String(length=125), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apikey')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('response')
    op.drop_table('dataset')
    # ### end Alembic commands ###
